# Generated by Django 4.0.2 on 2022-02-19 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('species', models.CharField(max_length=50)),
                ('weight', models.DecimalField(decimal_places=1, max_digits=30)),
                ('height', models.DecimalField(decimal_places=1, max_digits=20)),
                ('timestamp', models.DateTimeField(default=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('image', models.ImageField(upload_to='image')),
            ],
        ),
    ]
