# Generated by Django 4.0.2 on 2022-02-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0002_file_delete_records'),
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('species', models.CharField(max_length=50)),
                ('weight', models.DecimalField(decimal_places=1, max_digits=30)),
                ('height', models.DecimalField(decimal_places=1, max_digits=20)),
                ('file', models.FileField(upload_to='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
